config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated do
    root :to => 'wines#index', as: :authenticated
  end

  root 'wines#welcome'

  resources :wines do
    resources :reviews
    member do
      post :upcount
      post :downcount
      get :search
    end
  end
  resources :vineyards




end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :wine
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wines
end

app/models/vineyard.rb
class Vineyard < ActiveRecord::Base
  has_many :wines
  validates :name, presence: true
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_many :reviews
  belongs_to :vineyard
  belongs_to :user
  validates :name, presence: true
  validates :vineyard, presence: true

  SEARCH_CRITERIA = ['category', 'grape', 'occasion']

  CATEGORIES = ['Red', 'White', 'Rosé', 'Sparking', 'Dessert']
  GRAPES = ['Barolo',
            'Blush',
            'Bordeaux',
            'Cabernet',
            'Cabernet Franc',
            'Cabernet Sauvignon',
            'Champagne',
            'Chardonnay',
            'Chenin Blanc',
            'Chianti',
            'Gewürztraminer',
            'Malbec',
            'Merlot',
            'Moscato',
            'Muscat',
            'Other',
            'Petit Sirah',
            'Petit Verdot',
            'Pinot Gris',
            'Pinot Noir',
            'Port',
            'Riesling',
            'Roussanne',
            'Sangiovese',
            'Semillon',
            'Sauvignon Blanc',
            'Syrah',
            'Tempranillo',
            'Zinfandel']

  OCCASIONS = ['Every day', 'Nice dinner', 'Holiday', 'Celebration']

  validates :category, inclusion: { in: CATEGORIES }
  validates :grape, inclusion: { in: GRAPES }
  validates :occasion, inclusion: { in: OCCASIONS }


  include HTTParty

  # Generates the url needed for API requests.
  # Use URI.encode to strip spaces from search items so it's a valid URL
  def self.response(vineyard, varietal)
    api_key = ENV['WINE_API_KEY']
    api_url = "http://services.wine.com/api/beta2/service.svc/json/catalog?search=#{URI.encode(vineyard)}+#{URI.encode(varietal)}&apikey=#{api_key}"
    HTTParty.get(api_url)
  end

  ## Search fields for sorting on index page. Could be more DRY!

  def self.by(query_params)
# Query params will come in like the following:
#      {category: "Red"}
#      {grape: "Cabernet"}
#      {occasion: "Celebration"}
    Wine.where(query_params).order(:name)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    wine = Wine.find(params[:wine_id])
    @review = wine.reviews.new(description: review_params[:description])
    if @review.save
      flash[:notice] = 'Review saved!'
      redirect_to wine
    else
      flash.now[:alert] = @review.errors.full_messages.join(', ')
      render [:new, wine, @review]
    end
  end

  private

  # Rating is currently not being used in app; suggest adding to wine#show page.
  def review_params
    params.require(:review).permit(:description, :rating)
  end

end

app/controllers/vineyards_controller.rb
class VineyardsController < ApplicationController

  # This will add a new vineyard to the dropdown list so user can add new wine
  # if vineyard not already saved.  Redirect to same form.
  def create
    @vineyard = Vineyard.create(vineyard_params)
    redirect_to request.referer
  end

  def edit
    @vineyard = Vineyard.find(params[:id])
  end

  def update
    vineyard = Vineyard.find(params[:id])
    vineyard.update(vineyard_params)
    redirect_to :root
  end

  private

  # Storing address & country for vineyards as a possibility for app expansion
  def vineyard_params
    params.require(:vineyard).permit(:name, :address, :country)
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :welcome]

  def welcome
    @wines = Wine.all
  end

  def index
    # Unhide the next line if pagination desired for wine results.
    # Also need to add <%= will_paginate @posts %> to index page.
      # @wines = Wine.paginate(:page => params[:page], :per_page => 20)

      # Compare the params.keys (an array) with the SEARCH_CRITERIA array -
      # find the intersection (if there is one) and assign it to query_param
      query_param = (params.keys & Wine::SEARCH_CRITERIA).first

      if query_param.nil?
        # logger.debug "Get all wines"
        @wines = current_user.wines.order(:name)
      else
        # logger.debug "Get wines by #{params}"
        @wines = current_user.wines.by({query_param.to_sym => params[query_param]})
      end

      @wines_inventory = current_user.wines.map(&:on_hand).reduce(&:+)
  end

  def new
    @wine = current_user.wines.new
    # Update list of vineyard options based on current inventory
    @vineyard_options = Vineyard.all.map{ |vineyard| [vineyard.name, vineyard.id] }
    @vineyard = Vineyard.new
  end

  def show
    @wine = current_user.wines.find(params[:id])
    @review = @wine.reviews.new
  end

  # Search used for API request, passing in vineyard name and grape type
  def search
    @wine = Wine.find(params[:id])
    vineyard_name = @wine.vineyard.name
    varietal = @wine.grape
    @response = Wine.response(vineyard_name, varietal)
    render :search_results
  end

  def edit
    @wine = current_user.wines.find(params[:id])
    @vineyard_options = Vineyard.all.map{ |vineyard| [vineyard.name, vineyard.id] }
  end

  def update
    wine = current_user.wines.find(params[:id])
    wine.update(wine_params)
    redirect_to wine
  end

  # Find current wine, increase on_hand count by 1 for each click, save.
  def upcount
    wine = current_user.wines.find(params[:id])
    wine.on_hand += 1
    wine.save
    redirect_to wine
  end

  # Increases the consumption count by 1 and ALSO decreases on_hand count by 1.
  def downcount
    wine = current_user.wines.find(params[:id])
    # Verify that user has wine available to drink, if not, produce "no wine" message
    if wine.on_hand >= 1
      wine.on_hand -= 1
      wine.consumption += 1
      wine.save
      redirect_to wine
    else
      flash[:notice] = "Sorry, no wine available to drink!"
      redirect_to wine
    end
  end

  def create
    @vineyard_options = Vineyard.all.map{ |vineyard| [vineyard.name, vineyard.id] }
    @vineyard = Vineyard.new
    @wine = current_user.wines.new(wine_params)
    if @wine.save
      flash[:notice] = 'Wine successfully added to collection!'
      redirect_to root_path
    else
      flash.now[:alert] = @wine.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    wine = current_user.wines.find(params[:id])
    wine.destroy
    redirect_to root_path, notice: 'Wine was successfully removed.'
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :vineyard_id, :vintage, :description, :price, :category, :grape, :occasion, :on_hand, :consumption, :region )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Cellarage</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link type="text/css" media="screen" rel="stylesheet" href="responsive-tables.css" />
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  </head>

  <body>

    <div class="hero">
      <h1>CELLARAGE</h1>
    </div>

    <!-- Navigation bar -->

    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <% if user_signed_in? %>
          <h1><%= link_to "INVENTORY", root_path %></a></h1>
          <% end %>
        </li>
        <li class="toggle-topbar menu-icon"><a href="">Menu</a></li>
      </ul>
      <section class="top-bar-section">
        <% if user_signed_in? %>
          <ul class="left">
            <li class="has-dropdown"><a href="#">Categories</a>
              <ul class="dropdown">
                <% Wine::CATEGORIES.each do |category| %>
                  <li><%= link_to category, wines_path(category: category) %></li>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="left">
            <li class="has-dropdown"><a href="#">Varietals</a>
              <ul class="dropdown">
                <% Wine::GRAPES.each do |grape| %>
                  <li><%= link_to grape, wines_path(grape: grape) %></li>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="left">
            <li class="has-dropdown"><a href="#">Occasions</a>
              <ul class="dropdown">
                <% Wine::OCCASIONS.each do |occasion| %>
                  <li><%= link_to occasion, wines_path(occasion: occasion) %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        <% end %>

        <% if user_signed_in? %>
          <ul class="right">
            <li class="has-form"><%= link_to "Logged in as #{current_user.email}"%></li>
            <li class="divider"></li>
            <li class="has-form"><%= link_to 'Edit profile', edit_user_registration_path, class: 'button secondary' %></li>
            <li class="divider"></li>
            <li class="has-form"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button secondary' %></li>
          </ul>
        <!-- Nav bar login buttons if user is not yet signed in -->
        <% else %>
          <ul class="right">
            <li class="has-form"><%= link_to "Sign up", new_user_registration_path, class: 'button secondary' %></li>
            <li class="divider"></li>
            <li class="has-form"><%= link_to "Login", new_user_session_path, class: 'button secondary' %></li>
          </ul>
        <% end %>
      </section>

    </nav>

    <div class="row">
      <div class="large-12 columns">
        <div class="right">
        <br>
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <%= content_tag :div, msg, :class => "flash_#{name}" %>
          <% end %>
        <% end %>
        </div>

        <%= yield %>

      </div>
    </div>

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/vineyards/_vineyard_details.erb
<br><br>

<%= form_for @vineyard do |vineyard| %>

  <p>Edit vineyard details below:</p>

  <div class="row collapse">
    <div class="small-5 columns">
      <%= vineyard.label :name, 'Vineyard Name', class: 'right inline' %>
    </div>
    <div class="small-7 columns">
      <%= vineyard.text_field :name %>
    </div>
  </div>

  <div class="row collapse">
    <div class="small-2 columns">
      <%= vineyard.label :address, class: 'right inline' %>
    </div>
    <div class="small-4 columns">
      <%= vineyard.text_field :address %>
    </div>
    <div class="small-2 columns">
      <%= vineyard.label :country, class: 'right inline' %>
    </div>
    <div class="small-2 small-4 columns">
      <%= vineyard.text_field :country %>
    </div>
    <div class="medium-1 columns">
      <%= vineyard.submit 'Update vineyard', class: 'small button right simple' %>
    </div>
  </div>

<% end %>

app/views/vineyards/edit.html.erb
<%= render 'vineyard_details' %>

app/views/wines/_form.html.erb
<%= form_for @wine do |f| %>

  <br><hr><br><br>

  <%= f.label :vineyard_id, '**Select a winery from the list:' %>
  <%= f.select :vineyard_id, @vineyard_options.sort, include_blank: true %>

  <br><br>

  <h3>Add details about your wine</h3>

  <div class="row collapse">
    <div class="small-2 columns">
      <%= f.label :name, class: 'prefix radius' %>
    </div>
    <div class="small-4 columns">
      <%= f.text_field :name %>
    </div>
    <div class="small-2 columns">
      <%= f.label :vintage, class: 'prefix radius' %>
    </div>
    <div class="small-4 columns">
      <%= f.text_field :vintage %>
    </div>
  </div>

  <div class="row collapse">
    <div class="small-2 columns">
      <%= f.label :price, class: 'prefix radius' %>
    </div>
    <div class="small-4 columns">
      <%= f.text_field :price %>
    </div>
    <div class="small-2 columns">
      <%= f.label :on_hand, class: 'prefix radius' %>
    </div>
    <div class="small-4 columns">
      <%= f.text_field :on_hand %>
    </div>
  </div>

  <div class="row collapse">
    <div class="small-2 columns">
      <%= f.label :category, class: 'prefix radius' %>
    </div>
    <div class="small-10 columns">
      <%= f.select :category, Wine::CATEGORIES, include_blank: true %>
    </div>
  </div>

  <div class="row collapse">
    <div class="small-2 columns">
      <%= f.label :grape, class: 'prefix radius' %>
    </div>
    <div class="small-10 columns">
      <%= f.select :grape, Wine::GRAPES, include_blank: true %>
    </div>
  </div>

  <div class="row collapse">
    <div class="small-2 columns">
      <%= f.label :occasion, class: 'prefix radius' %>
    </div>
    <div class="small-10 columns">
      <%= f.select :occasion, Wine::OCCASIONS, include_blank: true %>
    </div>
  </div>

  <br>

  <%= f.submit 'Submit', class: 'small button' %>

<% end %>

app/views/wines/_vineyard_details.erb
<%= form_for @vineyard do |vineyard| %>

  <p>Is this a new vineyard?  If so, please add vineyard details below:</p>

  <div class="row collapse">
    <div class="small-5 columns">
      <%= vineyard.label :name, 'Vineyard Name', class: 'right inline' %>
    </div>
    <div class="small-7 columns">
      <%= vineyard.text_field :name %>
    </div>
  </div>

  <div class="row collapse">
    <div class="small-2 columns">
      <%= vineyard.label :address, class: 'right inline' %>
    </div>
    <div class="small-4 columns">
      <%= vineyard.text_field :address %>
    </div>
    <div class="small-2 columns">
      <%= vineyard.label :country, class: 'right inline' %>
    </div>
    <div class="small-2 small-4 columns">
      <%= vineyard.text_field :country %>
    </div>
    <div class="medium-1 columns">
      <%= vineyard.submit 'Add vineyard', class: 'small button right simple' %>
    </div>
  </div>

<% end %>

app/views/wines/edit.html.erb
<%= render 'form' %>

app/views/wines/index.html.erb
<br><br>
<h6>Welcome!  We're currently storing <%= @wines_inventory %> wines for you.</h6>
<br>
<h3>Wines currently in my cellar</h3>

<table class="responsive">
  <thead>
    <td>Vintage</td>
    <td>Name</td>
    <td>Vineyard</td>
    <td>Quantity</td>
    <td>Category</td>
    <td>Varietal</td>
    <td>Occasion</td>
  </thead>

  <% @wines.each do |wine| %>
    <% if wine.on_hand > 0 %>
      <tr>
        <td><%= wine.vintage %></td>
        <td><%= link_to wine.name, wine %></td>
        <td><%= wine.vineyard.name %></td>
        <td><%= wine.on_hand %></td>
        <td><%= wine.category %></td>
        <td><%=wine.grape %></td>
        <td><%= wine.occasion %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= link_to "Add a new wine to my collection", new_wine_path, class: 'button radius primary' %><br><br>

<hr>
<h3>Wines I need to restock</h3>

<table class="responsive">
  <thead>
    <td>Vintage</td>
    <td>Name</td>
    <td>Vineyard</td>
    <td>Consumed</td>
    <td>Category</td>
    <td>Varietal</td>
    <td>Review</td>
  </thead>

  <% @wines.each do |wine| %>
    <% if wine.on_hand <= 0 %>
      <tr>
        <td><%= wine.vintage %></td>
        <td><%= link_to wine.name, wine %></td>
        <td><%= wine.vineyard.name %></td>
        <td><%= wine.consumption %></td>
        <td><%= wine.category %></td>
        <td><%= wine.grape %></td>
        <td>
          <% if wine.reviews.present? %>
              <%= link_to "#{truncate(wine.reviews.first.description, length: 35)} (#{wine.reviews.count})", wine %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/wines/new.html.erb
<br>
<h3>Select your vineyard</h3>

<%= render 'vineyard_details' %>
<%= render 'form' %>

app/views/wines/search_results.html.erb
<br>

<h3>Similar wines by <%= @wine.vineyard.name %></h3>

<table>
  <thead>
    <td>Vineyard</td>
    <td>Region</td>
    <td>Highest Rating</td>
    <td>Label</td>
    <td>Varietal</td>

    <!-- Must incorporate wine.com logo/link when using API search.  Do not remove! -->
    <td>Purchase/More Information &nbsp;&nbsp; <a href="http://www.wine.com/" title="Wine.com the destination for Wine and Wine Gifts"><img src="http://cache.wine.com/images/logos/80x20_winecom_logo.png" alt="Wine.com the destination for Wine and Wine Gifts" /></a></td>
  </thead>

  <% @response["Products"]["List"].each do |response| %>

    <tr>
      <td><%= response["Name"] %></td>
      <td><%= response["Appellation"]["Name"] %></td>
      <td><%= response["Ratings"]["HighestScore"] %></td>
      <td><img src="<%= response["Labels"][0]["Url"] %>"></td>
      <td><%= response["Varietal"]["Name"] %></td>
      <td><%= link_to nil, response["Url"], :target => '_blank' %></td>
    </tr>
  <% end %>
</table>

app/views/wines/show.html.erb
<br>
<div class="panel">

  <h2><%= @wine.name %></h2>

  <br><br>
  <div class="row">
    <div class="medium-6 columns">
      <dl>
        <dt>Vineyard:</dt><dd> <%= @wine.vineyard.name %> (<em><%= link_to 'Edit vineyard', edit_vineyard_path(@wine.vineyard) %></em>)</dd>
        <dt>Vintage:</dt><dd> <%= @wine.vintage %> </dd>
        <dt>Region:</dt><dd> <%= @wine.region %> </dd>
        <dt>Price:</dt><dd> <%= number_to_currency(@wine.price) %> </dd>
        <dt>Category:</dt><dd> <%= @wine.category %> </dd>
        <dt>Grape:</dt><dd> <%= @wine.grape %> </dd>
        <dt>Occasion:</dt><dd> <%= @wine.occasion %> </dd>
      </dl>

      <em><%= link_to 'Edit wine details', edit_wine_path(@wine) %></em>

      <br><br>

      <em><%= link_to 'Delete this wine', @wine, method: :delete, data: { confirm: 'Are you sure?' } %></em>

    </div>

    <div class="medium-6 columns">
      <br><br>
      Available to drink: <h3><strong><%= @wine.on_hand %></strong></h3>
      Consumed: <h3><strong><%= @wine.consumption %></strong></h3>
      <br><br>
      <ul class = "button-group round">
        <li><%= button_to  "Add", upcount_wine_path, class: 'small button secondary' %></li>
        <li><%= button_to  "Drink", downcount_wine_path, class: 'small button secondary' %></li>
      </ul>
      <br><br>
    </div>

    <div class="center">
      <%= link_to "Like this wine? Search for similar wines by #{@wine.vineyard.name}.", search_wine_path(@wine), class: 'button' %>
    </div>
  </div>

  <hr>

  <h2>Reviews</h2>

  <% @wine.reviews.each do |review| %>
    <blockquote><%= review.description %></blockquote>
  <% end %>

</div>

<br>

<%= form_for [@wine, @review] do |f| %>
  <%= f.label :description, 'Add your review:'  %>
  <%= f.text_area :description  %>
  <%= f.submit 'Review' %>
<% end %>

<br><br>

app/views/wines/welcome.html.erb
  <br><br>
  <div align="center">
    <br>
    <img class="front_page_image" src="http://i.imgur.com/Mq5GHul.png">
    <h3>Members are storing <%= @wines.map(&:on_hand).reduce(&:+) %> wines in the cellar.</h3>
    <h4>(Collectively, we've consumed <%= @wines.map(&:consumption).reduce(&:+) %> bottles, cheers!)</h4>

    <br><br>
    <%= link_to "Log in now to manage your wines", new_user_session_path, class: 'button secondary' %>
  </div>